// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuestGiver.Data;

#nullable disable

namespace QuestGiver.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260403071119_MapVoteDecision")]
    partial class MapVoteDecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuestGiver.Data.Models.FriendGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsGeneratingQuests")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("FriendGroups");
                });

            modelBuilder.Entity("QuestGiver.Data.Models.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<Guid>("FriendGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FriendGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("QuestGiver.Data.Models.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpirationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RefreshToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("QuestGiver.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("NextLevelExperience")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuestGiver.Data.Models.UserFriendGroup", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FriendGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "FriendGroupId");

                    b.HasIndex("FriendGroupId");

                    b.ToTable("UserFriendGroups");
                });

            modelBuilder.Entity("QuestGiver.Data.Models.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ReceiveNotifications")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("QuestGiver.Data.Models.UserVote", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VoteId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("Decision")
                        .HasColumnType("boolean");

                    b.HasKey("UserId", "VoteId");

                    b.HasIndex("VoteId");

                    b.ToTable("UserVotes");
                });

            modelBuilder.Entity("QuestGiver.Data.Models.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("Decision")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Discriminator")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestId");

                    b.ToTable("Votes", (string)null);

                    b.HasDiscriminator();

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("QuestGiver.Data.Models.CompletionVote", b =>
                {
                    b.HasBaseType("QuestGiver.Data.Models.Vote");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("QuestGiver.Data.Models.SkipVote", b =>
                {
                    b.HasBaseType("QuestGiver.Data.Models.Vote");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("QuestGiver.Data.Models.Quest", b =>
                {
                    b.HasOne("QuestGiver.Data.Models.FriendGroup", "FriendGroup")
                        .WithMany("Quests")
                        .HasForeignKey("FriendGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestGiver.Data.Models.User", "User")
                        .WithMany("Quests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FriendGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuestGiver.Data.Models.Token", b =>
                {
                    b.HasOne("QuestGiver.Data.Models.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuestGiver.Data.Models.UserFriendGroup", b =>
                {
                    b.HasOne("QuestGiver.Data.Models.FriendGroup", "FriendGroup")
                        .WithMany("UserFriendGroups")
                        .HasForeignKey("FriendGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestGiver.Data.Models.User", "User")
                        .WithMany("UserFriendGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FriendGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuestGiver.Data.Models.UserSettings", b =>
                {
                    b.HasOne("QuestGiver.Data.Models.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("QuestGiver.Data.Models.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuestGiver.Data.Models.UserVote", b =>
                {
                    b.HasOne("QuestGiver.Data.Models.User", "User")
                        .WithMany("UserVotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestGiver.Data.Models.Vote", "Vote")
                        .WithMany("UserVotes")
                        .HasForeignKey("VoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vote");
                });

            modelBuilder.Entity("QuestGiver.Data.Models.Vote", b =>
                {
                    b.HasOne("QuestGiver.Data.Models.Quest", "Quest")
                        .WithMany("Votes")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("QuestGiver.Data.Models.FriendGroup", b =>
                {
                    b.Navigation("Quests");

                    b.Navigation("UserFriendGroups");
                });

            modelBuilder.Entity("QuestGiver.Data.Models.Quest", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("QuestGiver.Data.Models.User", b =>
                {
                    b.Navigation("Quests");

                    b.Navigation("Settings")
                        .IsRequired();

                    b.Navigation("Tokens");

                    b.Navigation("UserFriendGroups");

                    b.Navigation("UserVotes");
                });

            modelBuilder.Entity("QuestGiver.Data.Models.Vote", b =>
                {
                    b.Navigation("UserVotes");
                });
#pragma warning restore 612, 618
        }
    }
}
